In [1]:
import pandas as pd

In [3]:
raw = pd.read_csv("rewards.csv")
raw

,EventReward,VelBalToGoal,VelBalToSelfGoal,LiuToGoal,LiuToSelfGoal,VeltoBal,FaceBall,inAir
0,0.0,-0.062027,0.091829,2.311028,-2.355510,0.837457,-0.222743,0.00
1,0.0,-0.153048,0.037216,3.925850,-1.386617,1.474881,-0.336198,0.00
2,0.0,-0.063004,0.093143,2.310064,-2.353089,0.532892,-0.205088,0.15
3,0.0,-0.155238,0.037803,3.921815,-1.386039,1.098305,-0.357193,0.00
4,0.0,-0.063881,0.094287,2.309087,-2.350638,0.509982,-0.173734,0.15
...,...,...,...,...,...,...,...,...
57253,0.0,0.031634,0.285829,2.957304,-2.128103,0.381532,0.485800,0.15
57254,0.0,-0.487861,-0.012164,3.535454,-1.774688,0.099190,0.416895,0.00
57255,0.0,0.020274,0.292717,2.957814,-2.121272,0.365579,0.488251,0.15
57256,0.0,-0.498942,-0.005405,3.523842,-1.774861,0.189494,0.389005,0.00
57257,0.0,0.009008,0.299365,2.958101,-2.114305,0.349288,0.490402,0.15

In [5]:
raw.describe()

,EventReward,VelBalToGoal,VelBalToSelfGoal,LiuToGoal,LiuToSelfGoal,VeltoBal,FaceBall,inAir
count,57258.000000,57258.000000,57258.000000,57258.000000,57258.000000,57258.000000,57258.000000,57258.000000
mean,0.000724,0.001589,-0.000953,3.208508,-1.925105,0.220427,0.285682,0.131699
std,0.012638,0.229457,0.137674,0.721749,0.433049,0.318776,0.246759,0.049095
min,0.000000,-1.464280,-0.766109,2.098003,-3.036451,-1.207437,-0.499911,0.000000
25%,0.000000,-0.147273,-0.091213,2.577950,-2.243896,0.011188,0.194818,0.150000
50%,0.000000,0.003181,-0.001908,3.173951,-1.904371,0.213677,0.385146,0.150000
75%,0.000000,0.152021,0.088364,3.739827,-1.546770,0.417042,0.465785,0.150000
max,0.250000,1.276848,0.878568,5.060752,-1.258802,1.615801,0.499999,0.150000